/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ementor;

import javax.swing.JOptionPane;


public class Cadastros extends javax.swing.JFrame {

    /** Creates new form Cadastros */
    public Cadastros() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seletor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        TNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TCPF = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        TDataNascimento = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        TContato = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TMatricula = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TPeriodo = new javax.swing.JTextField();
        TDataAdmissao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TSalarioBruto = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Seletor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione uma Opção", "Aluno", "Professor" }));
        Seletor.setToolTipText("");
        Seletor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Seletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeletorActionPerformed(evt);
            }
        });

        jLabel1.setText("Nome*");

        TNome.setPreferredSize(new java.awt.Dimension(8, 21));

        jLabel2.setText("CPF*");

        jLabel3.setText("Data Nascimento *");

        jLabel4.setText("Contato *");

        jLabel5.setText("Matrícula*");

        jLabel6.setText("Data Admissão *");

        jLabel7.setText("Período*");

        jLabel8.setText("Salário Bruto *");

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Listar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TContato, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(TPeriodo)
                                .addGap(58, 58, 58)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(89, 89, 89)
                                .addComponent(jButton1)
                                .addGap(40, 40, 40)
                                .addComponent(jButton2))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(jLabel8))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(TSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(143, 143, 143)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addContainerGap(22, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Seletor, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(Seletor, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TDataAdmissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TContato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TSalarioBruto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TPeriodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(24, 24, 24))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SeletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeletorActionPerformed
        if (Seletor.getSelectedIndex()==1){
            jLabel5.setVisible(true);
            TMatricula.setVisible(true);            
            jLabel7.setVisible(true);
            TPeriodo.setVisible(true);
            
            jLabel6.setVisible(false);
            TDataAdmissao.setVisible(false);            
            jLabel8.setVisible(false);
            TSalarioBruto.setVisible(false);
        }
        else if (Seletor.getSelectedIndex()==2){
            jLabel5.setVisible(false);
            TMatricula.setVisible(false);            
            jLabel7.setVisible(false);
            TPeriodo.setVisible(false);
            
            jLabel6.setVisible(true);
            TDataAdmissao.setVisible(true);            
            jLabel8.setVisible(true);
            TSalarioBruto.setVisible(true);
        }
    }//GEN-LAST:event_SeletorActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Arquivo arq = new Arquivo();
        
        if (Seletor.getSelectedIndex()==0)
            JOptionPane.showMessageDialog(null,"Selecione uma Opção Válida!","Informação",JOptionPane.INFORMATION_MESSAGE);
        
        if (Seletor.getSelectedIndex()==1){
            
            if (TNome.getText().isEmpty()||TCPF.getText().isEmpty() ||TMatricula.getText().isEmpty()||TPeriodo.getText().isEmpty()||TDataNascimento.getText().isEmpty()||TContato.getText().isEmpty())                
              JOptionPane.showMessageDialog(null,"Preencha todos os campos","Informação",JOptionPane.WARNING_MESSAGE);
            
            else{
            Aluno [] Alunos = new Aluno [100];//Cria vetor para carregar os dados do formulário e posteriormente gravar em disco
            
            /*Seção de verificar existencia de arquivos físicos - executa somente uma vez */
            if (arq.lerDoDiscoIndiceI("indiceAluno.txt")==0){
               arq.salvarNoDiscoIndiceI(0, "indiceAluno.txt");
               arq.salvarNoDisco(Alunos, "alunos.txt");
              }
            /*Seção para recuperar no arquivo físico o último índice e também as informações salvas via vetor */
            int i = arq.lerDoDiscoIndiceI("indiceAluno.txt");
            Alunos = (Aluno []) arq.lerDoDisco(Alunos, "alunos.txt");
            
            /*Seção de copiar os dados dos campos do formulário para um objeto da classe Aluno */
            Aluno ObjetoAluno = new Aluno ();
           
            ObjetoAluno.setDados(TNome.getText(), TDataNascimento.getText(), 
                                 Long.parseLong(TCPF.getText()), 
                                 TContato.getText(),
                                 Long.parseLong(TMatricula.getText()),
                                 Integer.parseInt(TPeriodo.getText()));
            /*Seção para gravar os dados contidos no objeto, em uma posição do vetor, para o arquivo físico*/
            Alunos[i] = ObjetoAluno;
            i=i+1; 
            ObjetoAluno.imprimirDados();
            arq.salvarNoDiscoIndiceI(i, "indiceAluno.txt");
            arq.salvarNoDisco(Alunos, "alunos.txt");
            /*Seção para limpar os campos do formulário  */
            TNome.setText("");
            TCPF.setText("");
            TDataNascimento.setText("");
            TContato.setText("");
            TMatricula.setText("");
            TPeriodo.setText("");
            JOptionPane.showMessageDialog(null,"Cadastro finalizado!","Sucesso!",JOptionPane.PLAIN_MESSAGE);
            }
         }
        else if (Seletor.getSelectedIndex()==2){//Professor
            if (TNome.getText().isEmpty()||TCPF.getText().isEmpty() ||TDataNascimento.getText().isEmpty()||TContato.getText().isEmpty() ||TDataAdmissao.getText().isEmpty()||TSalarioBruto.getText().isEmpty())                
              JOptionPane.showMessageDialog(null,"Preencha todos os campos","Informação",JOptionPane.WARNING_MESSAGE);
            
            else{
            Professor [] professores = new Professor [100];//Cria vetor para carregar os dados do formulário e posteriormente gravar em disco
            
            //Seção de verificar existencia de arquivos físicos - executa somente uma vez
            if (arq.lerDoDiscoIndiceI("indiceProfessor.txt")==0){
               arq.salvarNoDiscoIndiceI(0, "indiceProfessor.txt");
               arq.salvarNoDisco(professores, "professores.txt");
              }
            /*Seção para recuperar no arquivo físico o último índice e também as informações salvas via vetor */
            int i = arq.lerDoDiscoIndiceI("indiceProfessor.txt");
            professores = (Professor []) arq.lerDoDisco(professores, "professores.txt");
            
            /*Seção de copiar os dados dos campos do formulário para um objeto da classe Aluno */
            Professor ObjetoProfessor = new Professor ();
            //setDados( String DataAdmissao, double SalarioBruto, String nome, String data, long cpf, String contato) {
            ObjetoProfessor.setDados( TDataAdmissao.getText() ,Integer.parseInt(TSalarioBruto.getText()),
                                      TNome.getText(), TDataNascimento.getText(), 
                                      Long.parseLong(TCPF.getText()), 
                                      TContato.getText());
            /*Seção para gravar os dados contidos no objeto, em uma posição do vetor, para o arquivo físico*/
            professores[i] = ObjetoProfessor;
            i=i+1; //proxima posição livre do vetor Academico a ser gravada para nova recuperação
            ObjetoProfessor.imprimirDados();
            arq.salvarNoDiscoIndiceI(i, "indiceProfessor.txt");//grava índice
            arq.salvarNoDisco(professores, "professores.txt");//grava dados contidos no vetor de objetos
            /*Seção para limpar os campos do formulário  */
            TNome.setText("");
            TCPF.setText("");
            TDataNascimento.setText("");
            TContato.setText("");
            TDataAdmissao.setText("");
            TSalarioBruto.setText("");
            JOptionPane.showMessageDialog(null,"Cadastro finalizado!","Sucesso!",JOptionPane.PLAIN_MESSAGE);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            ListarDados Tabelas = new ListarDados();
            Tabelas.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Cadastros().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Seletor;
    private javax.swing.JTextField TCPF;
    private javax.swing.JTextField TContato;
    private javax.swing.JTextField TDataAdmissao;
    private javax.swing.JTextField TDataNascimento;
    private javax.swing.JTextField TMatricula;
    private javax.swing.JTextField TNome;
    private javax.swing.JTextField TPeriodo;
    private javax.swing.JTextField TSalarioBruto;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    // End of variables declaration//GEN-END:variables

}
