/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ementor;

import javax.swing.table.DefaultTableModel;


public class ListarDados extends javax.swing.JFrame {

    /**
     * Creates new form ListaAcademicosProfessores
     */
    public ListarDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaAcademicos = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        TabelaAcademicos1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Alunos Cadastrados");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Professores Cadastrados");

        TabelaAcademicos.setBackground(new java.awt.Color(204, 204, 255));
        TabelaAcademicos.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaAcademicos.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabelaAcademicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Data Nascimento", "Telefone", "Matrícula", "Período"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAcademicos.setDebugGraphicsOptions(javax.swing.DebugGraphics.LOG_OPTION);
        TabelaAcademicos.setGridColor(new java.awt.Color(255, 255, 255));
        TabelaAcademicos.setSelectionBackground(new java.awt.Color(153, 153, 255));
        TabelaAcademicos.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(TabelaAcademicos);

        TabelaAcademicos1.setBackground(new java.awt.Color(204, 204, 255));
        TabelaAcademicos1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        TabelaAcademicos1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        TabelaAcademicos1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome do professor", "CPF", "Data nascimento", "Telefone", "Salário Bruto", "Salário Liquido", "Data de admissão"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAcademicos1.setToolTipText("");
        TabelaAcademicos1.setGridColor(new java.awt.Color(255, 255, 255));
        TabelaAcademicos1.setSelectionBackground(new java.awt.Color(153, 153, 255));
        TabelaAcademicos1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(TabelaAcademicos1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 431, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(430, 430, 430))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(411, 411, 411))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       Arquivo arq = new Arquivo ();
     
      /*Seção para copiar os dados do arquivo físico */ 
      Aluno [] Alunos = new Aluno [100];
      
      int i = arq.lerDoDiscoIndiceI("indiceAluno.txt");
      Alunos = (Aluno []) arq.lerDoDisco(Alunos, "alunos.txt");
      /*Seção para inserir os dados copiados para a tabela de academicos  */
      DefaultTableModel Tabela = (DefaultTableModel) TabelaAcademicos.getModel();
      for (int k = 0; k<i; k++)
          Tabela.addRow(new Object[] {Alunos[k].nome,Alunos[k].cpf,
                                      Alunos[k].dataNascimento,Alunos[k].contato,
                                      Alunos[k].getMatricula(),
                                      Alunos[k].getPeriodo()});
       
   
      /*Seção para copiar os dados do arquivo físico */ 
      Professor [] Professores = new Professor [100];
      
      int j = arq.lerDoDiscoIndiceI("indiceProfessor.txt");
      Professores = (Professor []) arq.lerDoDisco(Professores, "professores.txt");
      DefaultTableModel Tabela2 = (DefaultTableModel) TabelaAcademicos1.getModel();
      /*Seção para inserir os dados copiados para a tabela de academicos  */
      for (int k = 0; k<j; k++)
          Tabela2.addRow(new Object[] {Professores[k].nome,Professores[k].cpf,
                                      Professores[k].dataNascimento,
                                      Professores[k].contato,
                                      "R$"+Professores[k].getSalarioBruto(),
                                      "R$"+Professores[k].salarioLiquido(Professores[k].getSalarioBruto()),
                                      Professores[k].getDataAdmissao()});
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ListarDados().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaAcademicos;
    private javax.swing.JTable TabelaAcademicos1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
